// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjgHm5ZpOoshhNiL75vnWEh9cI567gxxo',
    appId: '1:932289214229:web:f8941eb7556251e0169b1c',
    messagingSenderId: '932289214229',
    projectId: 'flutter-food-recognizer',
    authDomain: 'flutter-food-recognizer.firebaseapp.com',
    storageBucket: 'flutter-food-recognizer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD91t8M0-bMM8O2FriPrFGCIrkEMtgUDEI',
    appId: '1:932289214229:android:ebc315fe7a771857169b1c',
    messagingSenderId: '932289214229',
    projectId: 'flutter-food-recognizer',
    storageBucket: 'flutter-food-recognizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhUT_-zf4iNIASejGiesQl_jbaZ8orVjI',
    appId: '1:932289214229:ios:3535c09f88a1b431169b1c',
    messagingSenderId: '932289214229',
    projectId: 'flutter-food-recognizer',
    storageBucket: 'flutter-food-recognizer.firebasestorage.app',
    iosBundleId: 'com.example.foodRecognizerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhUT_-zf4iNIASejGiesQl_jbaZ8orVjI',
    appId: '1:932289214229:ios:3535c09f88a1b431169b1c',
    messagingSenderId: '932289214229',
    projectId: 'flutter-food-recognizer',
    storageBucket: 'flutter-food-recognizer.firebasestorage.app',
    iosBundleId: 'com.example.foodRecognizerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjgHm5ZpOoshhNiL75vnWEh9cI567gxxo',
    appId: '1:932289214229:web:485896e1889e695f169b1c',
    messagingSenderId: '932289214229',
    projectId: 'flutter-food-recognizer',
    authDomain: 'flutter-food-recognizer.firebaseapp.com',
    storageBucket: 'flutter-food-recognizer.firebasestorage.app',
  );
}
